[Done]在 GitHub Action 中定时检测 EasyConnect 版本
docker-easyconnect/docker-easyconnect pull request #280
Opened 2023-08-03 10:39 UTC by redjumper

#273

2023-08-04 17:28 UTC, Hagb requested changes
感谢PR！

有时候需要在 EasyConnect 版本未更新的情况下重新构建镜像：
1. 仓库中的代码更新后，需要重新构建镜像。
2. `build-and-push-docker-image.yml` 还负责了 aTrust 镜像的构建。

我建议将新加入的功能（判断版本以及提交版本文件）独立出来另一个 yml 文件（可以[用 cron 来触发](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule)），然后再从那个文件[调用](https://docs.github.com/en/actions/using-workflows/reusing-workflows) `build-and-push-docker-image.yml`. 这样子既可以手动构建，也可以自动由版本更新触发构建。

以下代码供参考

```yml
name: Check EasyConnect versions

on:
  schedule:
    # runs every day
    # 19:40 (UTC) = 27:40 (UTC+8) = 3:40 tomorrow (UTC+8)
    - cron:  '40 19 * * *'

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compare pkg_version.xml
        id: compare
        run: |
          wget http://download.sangfor.com.cn/download/product/sslvpn/pkg/pkg_version.xml -O pkg_version_remote.xml
          if diff pkg_version.xml pkg_version_remote.xml >/dev/null; then
            echo "different=false" >> $GITHUB_OUTPUT
          else
            echo "different=true" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Replace pkg_version.xml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          cp pkg_version_remote.xml pkg_version.xml
          git add pkg_version.xml
          git commit -m "Update pkg_version.xml"
          git push
        if: steps.compare.outputs.different == 'true'
      - name: Rebuild EasyConnect
        uses: ./.github/workflows/build-and-push-docker-image.yml
        secrets: inherit
        if: steps.compare.outputs.different == 'true'
```
（注：如果改成使用 cron 来定时触发检测，那么在构建之前先提交新的 pkg_version.xml 可能会比较合适，如果新版安装包有使构建失败的变更，那么即使构建失败也不会因为没有提交新版 pkg_version.xml 而反复触发构建）

2023-08-15 05:56 UTC, redjumper commented
最近有点忙，发现你都改完了。。就使用cron来定时触发检测吧

2023-08-16 18:47 UTC, Hagb commented
> 最近有点忙，发现你都改完了。。就使用cron来定时触发检测吧

看起来还有些问题，见 https://github.com/Hagb/docker-easyconnect/actions 里面 cron test 那两个。（所以是供参考嘛）
我从 https://stackoverflow.com/a/76439748 学到一个测试 action 的方法，挺好用的（ #284 ）

2023-08-17 04:51 UTC, redjumper commented
看了下，在step中没法调用workflow。后面准备把Build And Push Docker Image改成aciton

2023-08-17 05:18 UTC, Hagb commented
workflow 好像也可以按照条件运行，类似于 #284 那种（不过我还没摸清楚）

2023-08-17 05:23 UTC, redjumper commented
workflow能按照条件运行，但不能在step中被调用
[https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations](url)
> Reusable workflows are called directly within a job, and not from within a job step. You cannot, therefore, use GITHUB_ENV to pass values to job steps in the caller workflow.

2023-08-17 05:41 UTC, Hagb commented
> workflow能按照条件运行，但不能在step中被调用

嗯。我的想法是版本检查后的重新构建能不能作为单独一个 job，根据版本检查结果来决定是否运行。当然把 Build And Push Docker Image 改成 Action 也是可以的，但是感觉工作量可能会更大一些。

2023-08-18 02:25 UTC, redjumper commented
> 嗯。我的想法是版本检查后的重新构建能不能作为单独一个 job，根据版本检查结果来决定是否运行。

这也是个思路，刚尝试了下，没执行到。要下下周再有时间看了

2023-10-12 13:19 UTC, redjumper commented
已经把原先的workflow重构成composite action。但是测试时不巧没通过，上游的包版本刚好变动了，现有的workflow执行应该也是失败。你这边先不merge，执行workflow试试

2023-10-14 17:11 UTC, Hagb commented
试了运行在 https://github.com/docker-easyconnect/docker-easyconnect/actions/runs/6518938312 ，cron-test 分支上，看起来比较顺利。在 https://github.com/docker-easyconnect/docker-easyconnect/commit/6e55729c4146b764ecff5c7c758414eba96dfd6f 设了一下权限，不知道在主分支跑的话是否需要。

2023-10-14 17:32 UTC, Hagb commented
在构建容器的过程中失败了，不过似乎是由于 debian 那边的变动引起的。这明天看看修一下 dockerfile。

2023-10-18 09:52 UTC, Hagb commented
已经运行成功了 https://github.com/docker-easyconnect/docker-easyconnect/actions/runs/6559017158 。
之前的失败是由于我的错误配置，已经在 b58674f04cea856006d558ab97219f2aff9629bc 修复。

2023-10-18 09:53 UTC, Hagb requested changes

2023-10-18 09:53 UTC, Hagb commented on .github/actions/build-and-push-docker-image/action.yml
> +    default: 'mips64le arm64 i386 amd6'
此处 `amd64` 写漏了个 4

2023-10-18 10:01 UTC, redjumper commented on .github/actions/build-and-push-docker-image/action.yml
> +    default: 'mips64le arm64 i386 amd6'
这里是漏了。.022下面的atrust_archs定义了，但代码里没有用到

2023-10-18 10:38 UTC, Hagb commented on .github/actions/build-and-push-docker-image/action.yml
> +    default: 'mips64le arm64 i386 amd6'
确实… 后面改成用 build-args/ 里面有没有对应配置来判断，atrust_archs 可以去掉了。

2023-10-28 01:17 UTC, closed without merging