优化保活逻辑
docker-easyconnect/docker-easyconnect pull request #367
Opened 2024-07-15 15:24 UTC by Einskai

部分无法使用ping的环境使用wget一个url来替代

2024-07-15 16:07 UTC, Hagb requested changes
感谢！wget 的参数可能需要修改一下。

2024-07-15 16:24 UTC, Einskai commented on docker-root/usr/local/bin/start.sh
> +		busybox wget -O /dev/null "$PING_ADDR_URL"
感谢建议，是我忽略了这些细节。

2024-07-15 16:32 UTC, Hagb approved these changes

2024-07-15 16:33 UTC, merged

2024-07-15 16:40 UTC, Einskai commented
刚刚试了一下，好像 -T （大写）会有问题 ，报“Segmentation fault (core dumped)”，不知道是什么原因。

2024-07-15 17:54 UTC, Hagb commented
> 刚刚试了一下，好像 -T （大写）会有问题 ，报“Segmentation fault (core dumped)”，不知道是什么原因。

确实，我这里也可以复现

2024-07-15 18:06 UTC, Hagb commented
> > 刚刚试了一下，好像 -T （大写）会有问题 ，报“Segmentation fault (core dumped)”，不知道是什么原因。
> 
> 确实，我这里在容器里也可以复现 ~，但在容器外（使用相同的版本）却不能复现~

哦，容器外使用相同的版本也可以复现。容器所用版本的 `busybox wget --help` 输出中没有 `-T` 选项。

可以使用 `timeout 10 busybox wget ...` 来实现类似的功能。另外我发现如果要让 wget 不输出报错，还是需要加上 `-o /dev/null`

2024-07-16 00:53 UTC, Einskai commented
> > > 刚刚试了一下，好像 -T （大写）会有问题 ，报“Segmentation fault (core dumped)”，不知道是什么原因。
> > 
> > 
> > 确实，我这里在容器里也可以复现 ~，但在容器外（使用相同的版本）却不能复现~
> 
> 哦，容器外使用相同的版本也可以复现。容器所用版本的 `busybox wget --help` 输出中没有 `-T` 选项。
> 
> 可以使用 `timeout 10 busybox wget ...` 而不用 `-T` 选项来实现类似的功能。另外我发现如果要让 wget 不输出报错，还是需要加上 `-o /dev/null`

那麻烦你来改一下啦😁