修复捕获信号
docker-easyconnect/docker-easyconnect pull request #385
Opened 2024-09-19 14:05 UTC by moeshin

解决问题
* `docker stop` 无法处理信号，只能[超时后强行杀死容器](https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop)。
* `trap` 不工作，无法调用 `sync_ec2volume` 同步配置。

方法来自：https://stackoverflow.com/a/46057188/10188914

2024-10-01 07:41 UTC, Hagb commented
感谢贡献！这个真是很细致啊。

2024-10-01 07:42 UTC, Hagb approved these changes

2024-10-01 07:44 UTC, Hagb requested changes

2024-10-01 07:44 UTC, Hagb commented on Dockerfile.vncless
> +CMD ["bash", "-c", "TYPE=x11 start.sh"]
这里应该需要使用 `env TYPE=x11` 或者 `bash -c "TYPE=x11 exec start.sh"`，否则可能有同样的问题？

2024-10-04 11:27 UTC, moeshin commented
```dockerfile
CMD ["env", "TYPE=x11", "start.sh"]
```
```text
> ps -e
    PID TTY          TIME CMD
      1 pts/0    00:00:00 start.sh
     60 ?        00:00:00 tinyproxy
     64 pts/0    00:00:00 socat
     98 pts/0    00:00:00 start-sangfor.s
    113 pts/1    00:00:00 sh
    119 pts/1    00:00:00 sh
    120 pts/1    00:00:00 bash
    734 pts/0    00:00:00 sleep
    735 pts/1    00:00:00 ps

> ps -ex
    PID TTY      STAT   TIME COMMAND
      1 pts/0    Ss+    0:00 /bin/bash /usr/local/bin/start.sh PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=b7ec0a389b0c TERM=xterm PING_INTERVAL=1800 HOME=/root TYPE=x11
     64 pts/0    S+     0:00 socat tcp-listen:20000,reuseaddr,fork tcp4:127.0.0.1:54530 HOSTNAME=b7ec0a389b0c PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect _=/usr/bin/socat
     98 pts/0    S+     0:00 /bin/bash /usr/local/bin/start-sangfor.sh HOSTNAME=b7ec0a389b0c PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 DISPLAY=:1 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect OLDPWD=/root/conf _=/usr/local/bin/start-sangfor.sh
    113 pts/1    Ss     0:00 /bin/sh -c [ -e /bin/bash ] && (/bin/bash || exit 0) || /bin/sh PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=b7ec0a389b0c TERM=xterm PING_INTERVAL=1800 HOME=/root
    119 pts/1    S      0:00 /bin/sh -c [ -e /bin/bash ] && (/bin/bash || exit 0) || /bin/sh PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=b7ec0a389b0c TERM=xterm PING_INTERVAL=1800 HOME=/root
    120 pts/1    S      0:00 /bin/bash HOSTNAME=b7ec0a389b0c HOME=/root TERM=xterm PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PING_INTERVAL=1800 PWD=/
    921 pts/0    S+     0:00 sleep 4 HOSTNAME=b7ec0a389b0c PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 DISPLAY=:1 SHLVL=1 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect OLDPWD=/root/conf _=/usr/bin/sleep
    922 pts/1    R+     0:00 ps -ex HOSTNAME=b7ec0a389b0c PING_INTERVAL=1800 PWD=/ HOME=/root TERM=xterm SHLVL=1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/bin/ps
```

```dockerfile
CMD ["bash", "-c", "TYPE=x11 exec start.sh"]
```

```text
> ps -e
    PID TTY          TIME CMD
      1 pts/0    00:00:00 start.sh
     59 ?        00:00:00 tinyproxy
     60 pts/0    00:00:00 socat
     98 pts/0    00:00:00 start-sangfor.s
    136 pts/1    00:00:00 sh
    142 pts/1    00:00:00 sh
    143 pts/1    00:00:00 bash
    696 pts/0    00:00:00 sleep
    697 pts/1    00:00:00 ps

> ps -ex
    PID TTY      STAT   TIME COMMAND
      1 pts/0    Ss+    0:00 /bin/bash /usr/local/bin/start.sh TYPE=x11 HOSTNAME=81660550ccf1 PING_INTERVAL=1800 PWD=/ HOME=/root TERM=xterm SHLVL=0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     60 pts/0    S+     0:00 socat tcp-listen:20000,reuseaddr,fork tcp4:127.0.0.1:54530 HOSTNAME=81660550ccf1 PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect _=/usr/bin/socat
     98 pts/0    S+     0:00 /bin/bash /usr/local/bin/start-sangfor.sh HOSTNAME=81660550ccf1 PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 DISPLAY=:1 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect OLDPWD=/root/conf _=/usr/local/bin/start-sangfor.sh
    136 pts/1    Ss     0:00 /bin/sh -c [ -e /bin/bash ] && (/bin/bash || exit 0) || /bin/sh PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=81660550ccf1 TERM=xterm PING_INTERVAL=1800 HOME=/root
    142 pts/1    S      0:00 /bin/sh -c [ -e /bin/bash ] && (/bin/bash || exit 0) || /bin/sh PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=81660550ccf1 TERM=xterm PING_INTERVAL=1800 HOME=/root
    143 pts/1    S      0:00 /bin/bash HOSTNAME=81660550ccf1 HOME=/root TERM=xterm PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PING_INTERVAL=1800 PWD=/
    819 pts/0    S+     0:00 sleep 4 HOSTNAME=81660550ccf1 PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 DISPLAY=:1 SHLVL=1 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect OLDPWD=/root/conf _=/usr/bin/sleep
    820 pts/1    R+     0:00 ps -ex HOSTNAME=81660550ccf1 PING_INTERVAL=1800 PWD=/ HOME=/root TERM=xterm SHLVL=1 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/bin/ps
```

```dockerfile
CMD ["bash", "-c", "TYPE=x11 start.sh"]
```
```text
> ps -e
    PID TTY          TIME CMD
      1 pts/0    00:00:00 start.sh
     59 ?        00:00:00 tinyproxy
     61 pts/0    00:00:00 socat
     98 pts/0    00:00:00 start-sangfor.s
    148 pts/1    00:00:00 sh
    154 pts/1    00:00:00 sh
    155 pts/1    00:00:00 bash
    726 pts/0    00:00:00 sleep
    727 pts/1    00:00:00 ps

> ps -ex
    PID TTY      STAT   TIME COMMAND
      1 pts/0    Ss+    0:00 /bin/bash /usr/local/bin/start.sh TYPE=x11 HOSTNAME=0fb7832633f3 PING_INTERVAL=1800 PWD=/ HOME=/root TERM=xterm SHLVL=0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/local/bin/start.sh
     61 pts/0    S+     0:00 socat tcp-listen:20000,reuseaddr,fork tcp4:127.0.0.1:54530 HOSTNAME=0fb7832633f3 PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect/resources VPN_CONF=/usr/share/sangfor/EasyConnect/resources/conf VPN_UI=/usr/share/sangfor/EasyConnect/EasyConnect _=/usr/bin/socat
     98 pts/0    S+     0:00 /bin/bash /usr/local/bin/start-sangfor.sh HOSTNAME=0fb7832633f3 PING_INTERVAL=1800 VPN_BIN=/usr/share/sangfor/EasyConnect/resources/bin TYPE=x11 PWD=/ HOME=/root ECHACK_NOWARN=1 VPN_ROOT=/usr/share/sangfor/EasyConnect TERM=xterm FORCE_OPEN_PORTS=54530 DISPLAY=:1 SHLVL=0 VPN_TUN=tun0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin VPN_RESOURCES=/usr/share/sangfor/EasyConnect [...]

2024-10-04 11:29 UTC, moeshin commented on Dockerfile.vncless
> +CMD ["bash", "-c", "TYPE=x11 start.sh"]
这三种都没有问题，用 env 好看点？

2024-10-08 00:53 UTC, Hagb approved these changes

2024-10-08 00:54 UTC, Hagb commented
感谢贡献！（抱歉最近比较忙，因此慢了几天回复。）

2024-10-08 00:55 UTC, merged

2024-10-08 01:09 UTC, Hagb commented on Dockerfile.vncless
> +CMD ["bash", "-c", "TYPE=x11 start.sh"]
> 这三种都没有问题，用 env 好看点？

你是对的，`bash -c "TYPE=x11 start.sh"` 确有 `bash -c "TYPE=x11 exec start.sh"` 的效果。 https://unix.stackexchange.com/questions/466496/why-is-there-no-apparent-clone-or-fork-in-simple-bash-command-and-how-its-done
原本我不知道 `bash -c ` 会有这样的行为（用于脚本里却是没有的）。